/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demoproj;

import subproj.*;

import org.junit.Test;
import static org.junit.Assert.*;

public class mainTest {

    GeneralClass myclass = new GeneralClass();    

    @Test public void testAdd() {
        Sample classUnderTest = new Sample(myclass);
        assertEquals(10, classUnderTest.AddTwoNumbers(5,5));
    }

    @Test public void testSub() {
        Sample classUnderTest = new Sample(myclass);
        assertEquals(0, classUnderTest.SubTwoNumbers(5,5));
    }

    @Test public void testMultiply() {
        Sample classUnderTest = new Sample(myclass);
        assertEquals(25, classUnderTest.MultiplyNumbers(5,5));
    }
}
