/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demoproj;
import subproj.*;

public class Sample {
    
    //General class defined without initiation
    GeneralClass myclass;

    //constructor with dependency injection
    Sample(GeneralClass cls)
    {
        myclass = cls;
    }

    public int AddTwoNumbers(int a, int b) {
        return myclass.addnum(a,b);
    }
    public int SubTwoNumbers(int a, int b) {
        return myclass.subnum(a,b);
    }
    public int MultiplyNumbers(int a, int b) {
        return myclass.multiply(a,b);
    }     
}
