/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package subproj;

import org.junit.Test;
import static org.junit.Assert.*;

public class subprojTest {

    GeneralClass myclass = new GeneralClass();

    @Test public void CheckAdd() {
        assertEquals(11, myclass.addnum(5,6));
    }

    @Test public void CheckSub() {
        assertEquals(4, myclass.subnum(10,6));
    }

    @Test public void CheckMultiply() {
        assertEquals(30, myclass.multiply(5,6));
    }

    @Test public void CheckDivision() {
        assertEquals("The result is:",2.0, myclass.divide(12,6),0);
    }
}
